// ── SEED DATA ─────────────────────────────────────────────────────

const DEFAULT_STAGES = [
  { id: 's1', label: 'Intercom Chat',           emoji: '💬' },
  { id: 's2', label: 'Data Collection (API)',   emoji: '🔌' },
  { id: 's3', label: 'AI Monitoring & Analysis',emoji: '🤖' },
  { id: 's-ai', label: 'Conversation Analysis', emoji: '🧠' },
  { id: 's4', label: 'Insights & Alerts',       emoji: '🔔' },
  { id: 's5', label: 'Reports + Tickets',       emoji: '📋' },
  { id: 's6', label: 'General Architecture',    emoji: '⚙️' },
];

const SEED = [
  { id: 'q1.1', stage: 's1', num: 'Q1.1', text: 'What defines a "completed" chat? Agent closes it, auto-closed after inactivity, or marked "resolved" in Intercom?' },
  { id: 'q1.2', stage: 's1', num: 'Q1.2', text: 'Are bot-handled conversations included or excluded from analysis?' },
  { id: 'q1.3', stage: 's1', num: 'Q1.3', text: 'If a completed conversation is reopened by a player, should the system re-analyze the updated conversation?' },
  { id: 'q1.4', stage: 's1', num: 'Q1.4', text: 'What is the estimated daily volume of completed conversations?' },
  { id: 'q1.5', stage: 's1', num: 'Q1.5', text: 'Are there specific teams, inboxes, or conversation tags that should be included or excluded?' },
  { id: 'q1.6', stage: 's1', num: 'Q1.6', text: 'Do we need to process historical conversations (backfill), or only from launch date forward?' },
  { id: 'q2.1', stage: 's2', num: 'Q2.1', text: 'What time should the daily data collection run?' },
  { id: 'q2.2', stage: 's2', num: 'Q2.2', text: 'Do we have existing Intercom API access? What permission level?' },
  { id: 'q2.3', stage: 's2', num: 'Q2.3', text: 'What data fields should be collected per conversation?' },
  { id: 'q2.4', stage: 's2', num: 'Q2.4', text: 'How should conversations containing multimedia (images, files, links) be handled?' },
  { id: 'q2.5', stage: 's2', num: 'Q2.5', text: 'Are there data privacy or compliance requirements (GDPR, PII masking)?' },
  { id: 'q2.6', stage: 's2', num: 'Q2.6', text: 'Where should raw conversation data be stored and for how long?' },
  { id: 'q3.1', stage: 's3', num: 'Q3.1', text: 'Should the system flag conversations where the player is dissatisfied at any point, or only where unresolved at the end?' },
  { id: 'q3.2', stage: 's3', num: 'Q3.2', text: 'Is there a severity scale (Low/Medium/High/Critical) or a simple Yes/No flag?' },
  { id: 'q3.3', stage: 's3', num: 'Q3.3', text: 'For unresolved case detection, should AI determine from conversation content, Intercom status, or both?' },
  { id: 'q3.4', stage: 's3', num: 'Q3.4', text: 'What qualifies as a "technical issue"?' },
  { id: 'q3.5', stage: 's3', num: 'Q3.5', text: 'For pattern identification, what timeframe — daily, weekly, or rolling window?' },
  { id: 'q3.6', stage: 's3', num: 'Q3.6', text: 'Should agent performance be evaluated as part of this analysis? If yes, what defines good vs. poor communication?' },
  { id: 'q3.7', stage: 's3', num: 'Q3.7', text: 'How should the system handle multilingual conversations? What languages are expected?' },
  { id: 'q3.8', stage: 's3', num: 'Q3.8', text: 'Should the AI provide specific quotes/snippets from conversations, or just summary-level assessments?' },
  { id: 'q3.9', stage: 's3', num: 'Q3.9', text: 'Is there an existing issue classification list, or should the AI generate categories dynamically?' },
  { id: 'q4.1', stage: 's4', num: 'Q4.1', text: 'What is the difference between AI Analysis (Stage 3) and Insights & Alerts?' },
  { id: 'q4.2', stage: 's4', num: 'Q4.2', text: 'What conditions should trigger an alert? Define specific scenarios.' },
  { id: 'q4.3', stage: 's4', num: 'Q4.3', text: 'How should alerts be delivered — email, Slack, SMS, push notification, or dashboard?' },
  { id: 'q4.4', stage: 's4', num: 'Q4.4', text: 'Should alerts be real-time (immediate) or batched into the daily report?' },
  { id: 'q4.5', stage: 's4', num: 'Q4.5', text: 'Who should receive alerts — team leaders only, QA managers, or specific roles based on alert type?' },
  { id: 'q5.1', stage: 's5', num: 'Q5.1', text: 'Daily Summary Email: Who are the recipients — single distribution list, per-team summaries, or role-based?' },
  { id: 'q5.2', stage: 's5', num: 'Q5.2', text: 'Daily Summary Email: What format — HTML email body, PDF attachment, or link to online dashboard?' },
  { id: 'q5.3', stage: 's5', num: 'Q5.3', text: 'Daily Summary Email: What information should be included?' },
  { id: 'q5.4', stage: 's5', num: 'Q5.4', text: 'Task/Ticket Creation: Which tool — Jira, Asana, Intercom Tickets, ClickUp, or another platform?' },
  { id: 'q5.5', stage: 's5', num: 'Q5.5', text: 'Task/Ticket Creation: One ticket per flagged conversation, or one aggregated ticket per day?' },
  { id: 'q5.6', stage: 's5', num: 'Q5.6', text: 'Task/Ticket Creation: What fields per ticket?' },
  { id: 'q5.7', stage: 's5', num: 'Q5.7', text: 'Task/Ticket Creation: How are tickets assigned — by team leader, round-robin, issue type, or manually?' },
  { id: 'q5.8', stage: 's5', num: 'Q5.8', text: 'What is the expected action from team leaders after receiving a ticket?' },
  { id: 'q5.9', stage: 's5', num: 'Q5.9', text: 'Monthly Report: Should this be fully AI-generated or human-curated using AI-provided data?' },
  { id: 'q5.10',stage: 's5', num: 'Q5.10',text: 'Monthly Report: What type of recommendations — agent coaching, process changes, product/technical fixes, or all?' },
  { id: 'q6.1', stage: 's6', num: 'Q6.1', text: 'Is there a feedback mechanism for team leaders to mark AI flags as accurate or false positive?' },
  { id: 'q6.2', stage: 's6', num: 'Q6.2', text: 'What should happen when the system encounters an error (API failure, AI timeout)?' },
  { id: 'q6.3', stage: 's6', num: 'Q6.3', text: 'Are there existing tools, dashboards, or reports this system should integrate with or replace?' },
  { id: 'q6.4', stage: 's6', num: 'Q6.4', text: 'What does success look like? Are there specific KPIs?' },
  { id: 'q6.5', stage: 's6', num: 'Q6.5', text: 'Is there a preferred timeline or phased rollout?' },
];

const SEED_THREADS = {
  'q1.1': [{ role: 'admin',  text: 'What defines a "completed" chat?', ts: '2026-03-06T09:00:00Z' }, { role: 'client', text: 'A Closed Chat (regardless of who closed it) = "Completed Chat"', ts: '2026-03-06T10:15:00Z' }],
  'q1.2': [{ role: 'admin',  text: 'Are bot-handled conversations included or excluded?', ts: '2026-03-06T09:01:00Z' }, { role: 'client', text: 'Included. When analyzing player dissatisfaction, any chat should be taken into consideration. For agent analysis, different story.', ts: '2026-03-06T10:16:00Z' }],
  'q1.3': [{ role: 'admin',  text: 'If a completed conversation is reopened by a player, should the system re-analyze it?', ts: '2026-03-06T09:02:00Z' }, { role: 'client', text: 'A closed chat can only be reopened by an agent. A snoozed chat can be reopened by the player, but it\'s not considered "completed." Re-analysis unlikely needed.', ts: '2026-03-06T10:17:00Z' }],
  'q1.4': [{ role: 'admin',  text: 'What is the estimated daily volume of completed conversations?', ts: '2026-03-06T09:03:00Z' }, { role: 'client', text: '600–700 common range; can go up to 1,000+ during promotions.', ts: '2026-03-06T10:18:00Z' }],
  'q1.5': [{ role: 'admin',  text: 'Are there specific teams, inboxes, or conversation tags to include or exclude?', ts: '2026-03-06T09:04:00Z' }, { role: 'client', text: 'No, not really.', ts: '2026-03-06T10:19:00Z' }],
  'q1.6': [{ role: 'admin',  text: 'Do we need to process historical conversations (backfill)?', ts: '2026-03-06T09:05:00Z' }, { role: 'client', text: 'Going back a few months would be helpful, but if it delays live analysis, prefer moving forward quickly.', ts: '2026-03-06T10:20:00Z' }],
  'q2.1': [{ role: 'admin',  text: 'What time should the daily data collection run?', ts: '2026-03-06T09:06:00Z' }, { role: 'client', text: '6 AM CET.', ts: '2026-03-06T10:21:00Z' }],
  'q2.2': [{ role: 'admin',  text: 'Do we have existing Intercom API access? What permission level?', ts: '2026-03-06T09:07:00Z' }, { role: 'client', text: 'Solved already.', ts: '2026-03-06T10:22:00Z' }],
  'q2.3': [{ role: 'admin',  text: 'What data fields should be collected per conversation?', ts: '2026-03-06T09:08:00Z' }, { role: 'client', text: 'Messages, tags, and custom attributes for sure. Will send example export of fields.', ts: '2026-03-06T10:23:00Z' }],
  'q2.4': [{ role: 'admin',  text: 'How should conversations containing multimedia be handled?', ts: '2026-03-06T09:09:00Z' }, { role: 'client', text: 'Could be error issue, KYC, or bonus promotion email. Need samples to determine which are reliable to analyze.', ts: '2026-03-06T10:24:00Z' }],
  'q2.5': [{ role: 'admin',  text: 'Are there data privacy or compliance requirements (GDPR, PII masking)?', ts: '2026-03-06T09:10:00Z' }, { role: 'client', text: 'Likely yes, but worth confirming with Maria and Alex to ensure alignment.', ts: '2026-03-06T10:25:00Z' }],
  'q3.1': [{ role: 'admin',  text: 'Should the system flag dissatisfaction at any point, or only if unresolved at end?', ts: '2026-03-06T09:12:00Z' }, { role: 'client', text: 'At any point.', ts: '2026-03-06T10:27:00Z' }],
  'q3.2': [{ role: 'admin',  text: 'Is there a severity scale or a simple Yes/No flag?', ts: '2026-03-06T09:13:00Z' }, { role: 'client', text: 'Stick with just flagging for now. Issues like inability to deposit, declined cards, or unclaimable bonus codes = critical flags.', ts: '2026-03-06T10:28:00Z' }],
  'q3.3': [{ role: 'admin',  text: 'For unresolved case detection — conversation content, Intercom status, or both?', ts: '2026-03-06T09:14:00Z' }, { role: 'client', text: 'A player may contact support multiple times. A single chat cannot reliably determine if case was ultimately resolved. Should be based on conversation content, not just status fields.', ts: '2026-03-06T10:29:00Z' }],
  'q3.4': [{ role: 'admin',  text: 'What qualifies as a "technical issue"?', ts: '2026-03-06T09:15:00Z' }, { role: 'client', text: '1. Login & Account Access\n2. Payments (deposit failures, declines)\n3. Game Functionality (bugs, crashes, loading issues)\n4. Bonuses (claim issues, code problems)\n5. Website & Navigation\n6. Device & Compatibility', ts: '2026-03-06T10:30:00Z' }],
  'q3.5': [{ role: 'admin',  text: 'For pattern identification, what timeframe — daily, weekly, or rolling window?', ts: '2026-03-06T09:16:00Z' }, { role: 'client', text: 'Track weekly and monthly trends. Monitor daily as well; flag anomalies outside normal range immediately. Include all patterns in daily, weekly, and monthly reports.', ts: '2026-03-06T10:31:00Z' }],
  'q3.6': [{ role: 'admin',  text: 'Should agent performance be evaluated? What defines good vs. poor communication?', ts: '2026-03-06T09:17:00Z' }, { role: 'client', text: 'Yes, but this will come at a later stage. Need time to carefully define good vs. poor communication.', ts: '2026-03-06T10:32:00Z' }],
  'q3.7': [{ role: 'admin',  text: 'How should the system handle multilingual conversations? What languages are expected?', ts: '2026-03-06T09:18:00Z' }, { role: 'client', text: 'Arabic, German, Greek, English, Finnish, French, Italian, Norwegian, Portuguese.', ts: '2026-03-06T10:33:00Z' }],
  'q3.8': [{ role: 'admin',  text: 'Should the AI provide specific quotes/snippets, or just summary-level assessments?', ts: '2026-03-06T09:19:00Z' }, { role: 'client', text: 'For player dissatisfaction: summary-level assessments usually sufficient. For agent evaluation: include actual conversation snippets for actionable feedback.', ts: '2026-03-06T10:34:00Z' }],
  'q3.9': [{ role: 'admin',  text: 'Existing issue classification list, or should AI generate categories dynamically?', ts: '2026-03-06T09:20:00Z' }, { role: 'client', text: "Don't have predefined list yet. Start with whatever AI initially generates, then formalize once we have data. Still allow AI to flag anything outside those categories.", ts: '2026-03-06T10:35:00Z' }],
  'q4.1': [{ role: 'admin',  text: 'What is the difference between AI Analysis (Stage 3) and Insights & Alerts?', ts: '2026-03-06T09:21:00Z' }, { role: 'client', text: 'Stage 3 = processing/analysis focus. Insights = feedback/reports (daily, weekly, monthly summaries). Alerts = separate flags for critical issues needing immediate attention.', ts: '2026-03-06T10:36:00Z' }],
  'q5.4': [{ role: 'admin',  text: 'Task/Ticket Creation: Which tool?', ts: '2026-03-06T09:25:00Z' }, { role: 'client', text: 'Asana.', ts: '2026-03-06T10:40:00Z' }],
  'q5.5': [{ role: 'admin',  text: 'One ticket per flagged conversation, or one aggregated ticket per day?', ts: '2026-03-06T09:26:00Z' }, { role: 'client', text: 'One ticket per flagged conversation. If batched, group conversations with same core issue.', ts: '2026-03-06T10:41:00Z' }],
  'q5.6': [{ role: 'admin',  text: 'What fields per ticket?', ts: '2026-03-06T09:27:00Z' }, { role: 'client', text: 'Each ticket should include: player account link, Intercom conversation link, issue summary, triggering snippet, recommended action.\n\nFor agent performance: master ticket per agent with individual flagged instances.\nFor player issues: master per category with flagged conversations grouped.', ts: '2026-03-06T10:42:00Z' }],
  'q5.7': [{ role: 'admin',  text: 'How are tickets assigned?', ts: '2026-03-06T09:28:00Z' }, { role: 'client', text: 'All tickets should be assigned directly to val@roosterpartners.com.', ts: '2026-03-06T10:43:00Z' }],
  'q5.8': [{ role: 'admin',  text: 'What is the expected action from team leaders after receiving a ticket?', ts: '2026-03-06T09:29:00Z' }, { role: 'client', text: 'Depends on ticket type: review, coach agent, follow up with player, or escalate. Define and discuss at a later stage.', ts: '2026-03-06T10:44:00Z' }],
  'q5.9': [{ role: 'admin',  text: 'Monthly Report: fully AI-generated or human-curated?', ts: '2026-03-06T09:30:00Z' }, { role: 'client', text: 'Fixed structure each month, but content reflects AI analysis. Structure is fixed, insights/feedback vary based on AI output.', ts: '2026-03-06T10:45:00Z' }],
  'q5.10':[{ role: 'admin',  text: 'Monthly Report: What type of recommendations?', ts: '2026-03-06T09:31:00Z' }, { role: 'client', text: 'All types: agent coaching, process changes, product/technical fixes. Can adjust after seeing actual report output.', ts: '2026-03-06T10:46:00Z' }],
  'q6.1': [{ role: 'admin',  text: 'Is there a feedback mechanism for team leaders to mark AI flags as accurate or false positive?', ts: '2026-03-06T09:32:00Z' }, { role: 'client', text: "Don't currently have mechanism, but would be useful for tracking accuracy and improving AI over time.", ts: '2026-03-06T10:47:00Z' }],
  'q6.2': [{ role: 'admin',  text: 'What should happen when the system encounters an error?', ts: '2026-03-06T09:33:00Z' }, { role: 'client', text: 'Automatic retry logic (second and third attempts 15–20 minutes later). Backup mechanism to ensure daily summaries, insights, and alerts from previous day are delivered.', ts: '2026-03-06T10:48:00Z' }],
  'q6.3': [{ role: 'admin',  text: 'Existing tools or dashboards this system should integrate with or replace?', ts: '2026-03-06T09:34:00Z' }, { role: 'client', text: 'No existing dashboards. Everything manual so far (live chat QA, ticket tracking). This system replaces all manual work, not an existing tool.', ts: '2026-03-06T10:49:00Z' }],
  'q6.4': [{ role: 'admin',  text: 'What does success look like? Are there specific KPIs?', ts: '2026-03-06T09:35:00Z' }, { role: 'client', text: '(1) Reliably detect actual player issues with high accuracy; learn to avoid escalating non-actionable flags (e.g., unhappy about denied bonus).\n(2) Maintain consistent structure in reports for easy interpretation.', ts: '2026-03-06T10:50:00Z' }],
};

const PRE_RESOLVED = [
  'q1.1','q1.2','q1.3','q1.4','q1.5','q1.6',
  'q2.1','q2.2','q2.3','q2.4','q2.5',
  'q3.1','q3.2','q3.3','q3.4','q3.5','q3.6','q3.7','q3.8','q3.9',
  'q4.1',
  'q5.4','q5.5','q5.6','q5.7','q5.8','q5.9','q5.10',
  'q6.1','q6.2','q6.3','q6.4',
];
